language: java

sudo: false

jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "rigs-it" # the key of the org you chose at step #3
    token:
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar