language: java
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: rigs-it
    token:
      secure: "TItleDCGbsUHjFa6aPmI78BB2QhnDldEYVmZXcp7g3c4us/as3I06NgtkvkMjMd+waJp0/EhqkxW0sNT4QNyzWMD3QrDjVyJIoxg3dNaQ4qSXu+XSsngzELM8q2z6oGm5TB2uDTiO4/tNhcpQgSqgtmw7KTZA2lOG8iMBSQWEVcgowP7iWRzT2nrJkWbmiGh53tvvOgkQYJ/B+oYy/QMftYGbvkEqLGgK1QngnSyQfkFzKNfXEa52be4+lg66n2r51Dqh2av0hiENthl9uliq3rVjiZh3ffdbWh1S4gIeFGoEh1D69rn1Wp9jl4TKktuc3noFOOdy60N3tP6ncjMZhHVMDg0gxF+9N7n+nC453z6XPTgS3CaMiZX+gdkkMzcyS2qxjivYt7xV4kDUu48hYvQVMZ7fkAxceNhZTFfEKgT+M9hxDWY3w0aZW30B+oO42nLy3/ILmZl/DZlrAYIUuCa8kODdVmehHll4ijXaFGlf1q2SBCRMlDuo8OIXFWVcawGBeG8YX17Pe2g10wcI2GHyEftmd5QBdV2s3PbPSUe/xyQR2i4XAQPq2sBWnGh3I9jSB7+MOUlQZbmCYcKc1wsG1IfQluONRtVvWnWk3kJcgRkIZWF2RjgnoK+GJzK2x/0MTLIoEL2msUg5FslZLZKuQcANRmrHoonxBfnmCo="

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    